package constant

const (
	GetSelfUserInfo = "/user/get_self_user_info" //todo
	GetUsersInfoRouter                   = "/user/get_user_info"
	UpdateSelfUserInfoRouter                = "/user/update_self_user_info" //todo
	AddFriendRouter                     = "/friend/add_friend"
	GetFriendInfoRouter                 = "/friend/get_friends_info"
	GetFriendApplicationListRouter      = "/friend/get_friend_apply_list"
	GetSelfApplicationListRouter        = "/friend/get_self_apply_list"
	DeleteFriendRouter                  = "/friend/delete_friend"
	GetFriendListRouter                 = "/friend/get_friend_list"
	GetBlackListRouter                  = "/friend/get_blacklist"
	AddFriendResponse                   = "/friend/add_friend_response"
	AddBlackListRouter                  = "/friend/add_blacklist"
	RemoveBlackListRouter               = "/friend/remove_blacklist"
	SetFriendComment                    = "/friend/set_friend_comment"
	SendMsgRouter                       = "/chat/send_msg"
	PullUserMsgRouter                   = "/chat/pull_msg"
	PullUserMsgBySeqRouter              = "/chat/pull_msg_by_seq"
	NewestSeqRouter                     = "/chat/newest_seq"
	TencentCloudStorageCredentialRouter = "/third/tencent_cloud_storage_credential"
	//group
	CreateGroupRouter                  = "/group/create_group"
	SetGroupInfoRouter                 = "/group/set_group_info"
	JoinGroupRouter                    = "/group/join_group"
	QuitGroupRouter                    = "/group/quit_group"
	GetGroupsInfoRouter                = "/group/get_groups_info"
	GetGroupMemberListRouter           = "/group/get_group_member_list"
	GetGroupAllMemberListRouter        = "/group/get_group_all_member_list"
	GetGroupMembersInfoRouter          = "/group/get_group_members_info"
	InviteUserToGroupRouter            = "/group/invite_user_to_group"
	GetJoinedGroupListRouter           = "/group/get_joined_group_list"
	KickGroupMemberRouter              = "/group/kick_group"
	TransferGroupRouter                = "/group/transfer_group"
	GetGroupApplicationListRouter      = "/group/get_group_applicationList"
	AcceptGroupApplicationRouter       = "/group/group_application_response"
	RefuseGroupApplicationRouter       = "/group/group_application_response"
	SetReceiveMessageOptRouter         = "/conversation/set_receive_message_opt"
	GetReceiveMessageOptRouter         = "/conversation/get_receive_message_opt"
	GetAllConversationMessageOptRouter = "/conversation/get_all_conversation_message_opt"
)
